# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c05abd3aca6d0dd7e2eec19db20bc91d673eb0dee37af0801daf5765211002b7dcd9078709054832d21d74b8385a3b81096610ae3cede40c3f86c79ea38b987e

test:
  secret_key_base: 0769da69eaa34e0fc10b31f426c24ff36547128d59e782426bbfdfd7a9040d4fc6c0f28f3e571c8aa148b9261d1093ee241634d782ce306e22264c2da3f95611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
